# Copyright 2026 Eckstein GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ---------------------------------------------------------------------------
# MODIFICATION NOTICE
# New file, not present in upstream OpenArm.
# ---------------------------------------------------------------------------
"""Generate the CRC-8 table used for the TLE5012B safety word and CRCPAR.

Polynomial 0x1D, init 0xFF, MSB first, no reflection; the final value is
inverted by the caller, not by the table (spec protocol-spec.md section 2.2).
A table is used rather than the bitwise loop because the safety word is checked
on every angle transaction: 123 cycles against roughly 1000 (section 8.3).
"""
t = []
for b in range(256):
    c = b
    for _ in range(8):
        c = ((c << 1) ^ 0x1D) & 0xFF if (c & 0x80) else (c << 1) & 0xFF
    t.append(c)
lines = [", ".join("0x%02X" % v for v in t[i:i + 12]) for i in range(0, 256, 12)]
with open("src/ker_crc8.inc", "w") as f:
    f.write("/* generated by tools/gen_crc8.py: CRC-8 poly 0x1D, MSB first */\n")
    f.write(",\n".join(lines) + "\n")
print("src/ker_crc8.inc: 256 entries")
