# Copyright 2026 Eckstein GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ---------------------------------------------------------------------------
# MODIFICATION NOTICE
# New file, not present in upstream OpenArm.
# ---------------------------------------------------------------------------
"""Generate the quarter-wave Q15 sine table for ker_comp.c and prove its 16-bit bound.

The interpolation in ker_sin_q15() computes (a1 - a0) * frac + round in uint16_t. That is only
correct if the worst case fits in 16 bits, which depends on the table resolution. This script
computes the bound from the actual table and emits it, and ker_comp.c static-asserts on it,
so changing KER_SIN_SEG_BITS can never silently reintroduce an overflow.
"""
import math, sys
for bits in (6, 7):
    n = 1 << bits
    shift = 14 - bits
    v = [round(math.sin(i / n * math.pi / 2) * 32767) for i in range(n + 1)]
    v.append(v[n])                                   # pad: idx+1 stays in bounds at idx == n
    steps = [v[i + 1] - v[i] for i in range(n)]
    assert min(steps) >= 0, "bound assumes a non-decreasing quarter wave"
    max_step = max(steps)
    worst = max_step * ((1 << shift) - 1) + (1 << (shift - 1))
    with open(f"ker_sinq{bits}.inc", "w") as f:
        f.write(f"/* generated by gen_sinq.py: {n} segments, {len(v)} entries, max step {max_step},\n"
                f"   worst interpolation product {worst} ({'fits' if worst <= 0xFFFF else 'OVERFLOWS'} uint16) */\n")
        f.write(",\n".join(", ".join(str(x) for x in v[i:i + 12]) for i in range(0, len(v), 12)) + "\n")
    with open(f"ker_sinq{bits}_bound.inc", "w") as f:
        f.write(f"#define KER_SIN_INTERP_WORST {worst}UL\n")
    print(f"{bits}: {n} segments, {2*len(v)} bytes, max step {max_step}, worst product {worst}",
          "fits uint16" if worst <= 0xFFFF else "DOES NOT fit uint16")
